version: '3'

services:
  astro-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    restart: unless-stopped
    # 如果有环境变量需要设置
    # environment:
    #   - NODE_ENV=production
